# Generated by Django 4.1.7 on 2023-03-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='BlogPost',
        ),
    ]
